### ISSUE TITLE
Determine Version of Mysql, apache, and php

### ISSUE THREAD

**Issue by jpsider** [BelayTechnologies/Belay-Device-Python#3]

**Comment by jtlitch** [comment]
MySQL Version: 15.1 Distrib 10.0.13-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by jtlitch** [comment]
Apache version 2.4.10 (Linux/SUSE)

**Comment by jtlitch** [comment]
PHP version 5.6.1 with Zend Engine v2.6.0

**Comment by jtlitch** [comment]
It is even easier than the documentation makes it. It can all be done through the base install DVD.

OpenSUSE 13.2 x86_64
Accept all defaults
- Gnome Desktop

Username: device
Password: {password}

Final review before installation
Under "Firewall and SSH"
- Disable firewall
- Enable ssh
  Under "Software"
- under server functions select WEB and LAMP server
- under development select Python development

TOTAL install should be roughly 3.5 GB

**Comment by jtlitch** [comment]
Added phpMyAdmin for good measure.
zypper install phpMyAdmin
